name: km/quote
typeName: km_quote
group: km_special
prefixFields: true
prefixType: full
fields:

  -
    identifier: header
    useExistingField: true
    label: Titel(intern)
    

  -
    identifier: bodytext
    type: Textarea
    label: 'Zitat-Text'
    useExistingField: true
  


basics:
  - TYPO3/Appearance
  - TYPO3/Links